version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    poetry: "2.1.3"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - method: poetry
      extras: ["docs"]

formats:
  - pdf