[tool.poetry]
name = "atmodeller"
version = "0.1.0"
description = "Computes chemical equilibrium of volatiles between a rocky interior and atmosphere"
authors = ["Dan J Bower <djbower@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10, <3.12"
scipy = "^1.10.1"
numpy = "^1.24.3"
pandas = "^2.0.1"
jupyter = "^1.0.0"
thermochem = "^0.8.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pylint = "^2.17.3"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 99 # override black's default line-length

[tool.isort]
# make it compatible with black
profile = "black"