[tool.poetry]
name = "atmodeller"
version = "0.1.0"
description = "Computes chemical equilibrium of volatiles between a rocky interior and atmosphere"
authors = ["Dan J Bower <djbower@users.noreply.github.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scipy = "^1.11.4"
numpy = "^1.26.3"
pandas = "1.3.5"
thermochem = { git = "https://github.com/ExPlanetology/thermochem.git" }
openpyxl = "^3.1.2"
molmass = "^2023.4.10"
scikit-learn = "^1.4.0"
ipykernel = "^6.29.0"
matplotlib = "^3.8.2"
jupyter = "^1.0.0"
seaborn = "^0.13.1"
cmcrameri = "^1.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
sphinx-rtd-theme = "^2.0.0"
sphinx = "^7.2.6"
sphinxcontrib-bibtex = "^2.6.2"
setuptools = "^69.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"