name: Run Pre-commit Hooks

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          poetry install

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files

      - name: Test with pytest
        run: pytest
